# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.20.074242'

RELEASE_GIT_HEAD = '92d4db6b2e6085f52747a5c1169bf28cbaaae6c1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yinyajiang/yt-dlp'

ORIGIN = 'yinyajiang/yt-dlp'

_pkg_version = '2025.08.20.074242'
