# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.16.014956'

RELEASE_GIT_HEAD = '1a264f67d15746b3abdbdb3c5ade91d9116bc916'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yinyajiang/yt-dlp'

ORIGIN = 'yinyajiang/yt-dlp'

_pkg_version = '2025.10.16.014956'
