# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.02.014229'

RELEASE_GIT_HEAD = '76dcd01754d1e8d0377d79463dedef4262544bd1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'yinyajiang/yt-dlp'

ORIGIN = 'yinyajiang/yt-dlp'

_pkg_version = '2024.12.02.014229'
